### ISSUE TITLE
Community Diligence Review of Antalpha Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#110]
@nj-steve
Allocator compliance report: https://compliance.allocator.tech/report/f03019858/1721403387/report.md

Allocations look good

No sign of KYC

Example 1: https://github.com/Antalpha-Web3/Ant-Steve/issues/5

CID report: https://check.allocator.tech/report/Antalpha-Web3/Ant-Steve/issues/5/1721403835131.md

SPs not matching those provided by client. Retrievals at 0% but client received 3.5PiBs DataCap

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
-- | -- | -- | -- | -- | -- | --
f02826123new | Shenzhen, Guangdong, CNChina Mobile communications corporation | 444.34 TiB | 29.26% | 444.34 TiB | 0.00% | 0.02%
f02826234new | Guangzhou, Guangdong, CNChina Mobile communications corporation | 351.06 TiB | 23.11% | 351.06 TiB | 0.00% | 5.72%
f03078086new | Shenzhen, Guangdong, CNChina Unicom Guangdong IP network | 537.53 TiB | 35.39% | 537.53 TiB | 0.00% | 0.00%
f02825444 | Singapore, Singapore, SGThe Constant Company, LLC | 94.56 TiB | 6.23% | 94.56 TiB | 0.00% | 0.00%
f02825855 | Paripark, Seoul, KRThe Constant Company, LLC | 91.34 TiB | 6.01% | 91.34 TiB | 0.00% | 0.00%

**Comment by nj-steve** [comment]
Hi @filecoin-watchdog @Kevin-FF-USA 
1. I have communicated with client about the retrieval problem. These SP have stored the retrieval data. Unsupported may be due to program problems, some incompatible, some optimization, are being solved. It has been communicated to the client a long time ago that if SP does not solve the search problem, it will not be able to continue to get new deals.
2. More excellent SPs is comming.The report will see more SPs and more copies.
3. About kyc ,  we've verified zklion's offial email.
<img width="890" alt="image" src="https://github.com/user-attachments/assets/96199f6a-20bf-4227-b52d-07d8d1a5c0d1">

**Comment by nj-steve** [comment]
If you have any other suggestions, I will cooperate fully.

**Comment by kevzak** [comment]
Hi @nj-steve - we think it is important for all clients to start providing more details of data preparation. See my proposal https://github.com/filecoin-project/Allocator-Governance/issues/125  any thoughts?

**Comment by nj-steve** [comment]
Hi Kevin @kevzak
I really think your proposal is very good. I have been participating in the Filecoin project for 4 years, and I have been thinking about how to use data.

First, there is the issue of retrieving data. Because there is no contractual agreement and only relying on system management, this cannot last long. We know retrieving data has been a big issue in community. I think only by designing a reward mechanism we can ensure the retrieval rate of miners. If there are rewards, miners will be happy to support retrieve.

The second is the issue of using data. We need to store some data that can be used by some people. When applying, we must write down how the data will be used, what benefits it has, and other characteristics. Convenient for users who need it to use.

Third, there is the issue of data authenticity. This requires self-demonstration or community inspection. As you said, we conduct pollutant surveys on the data. The data for this demonstration comes from this data set. I will also conduct data authenticity checks later.

**Comment by nj-steve** [comment]
https://github.com/Antalpha-Web3/Ant-Steve/issues/9

https://check.allocator.tech/report/Antalpha-Web3/Ant-Steve/issues/9/1725592536111.md

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/bbbc98a8-ef01-42cc-876e-e9ad9209048e">

Hi, The new client SPs support retrieval rate is high.

Others they now is in the process of fixes and updates.

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is partially in compliance with [their application.](https://github.com/filecoin-project/notary-governance/issues/1052)

Specifically:
- Mixed evidence of diligence with clients (no verification of client claims)
- Subsequent allocations given despite noncompliant client deal-making, with minimal allocator intervention through comments
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)


Given this mixed review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 2.5 of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.


**@NJ-steve can you verify that you will enforce program and allocator requirements? 
(for example: public diligence, tranche schedules, and public scale retrievability like Spark).** 

Please reply here with acknowledgement and any additional details for our review.

**Comment by nj-steve** [comment]
Thank you @galen-mcandrew . I will collect the latest data. I have contacted with the previous client, and some of the SPs ordered by them have already supported retrieval, while some are still under repair.

**Comment by nj-steve** [comment]
https://github.com/Antalpha-Web3/Ant-Steve/issues/5
<img width="544" alt="image" src="https://github.com/user-attachments/assets/ad8287bd-b1f4-4a6f-b265-6ffd320b42fc">

<img width="580" alt="image" src="https://github.com/user-attachments/assets/cc564eec-d74e-48b4-953b-5d71c8b14b0d
This client data replication looks so healthy. The number of supported retrieval SPs is increasing and the average retrieval success rate is also increasing.  More SPs are under  repairing retrieval .

**Comment by nj-steve** [comment]
https://github.com/Antalpha-Web3/Ant-Steve/issues/9
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/e5590fbe-358a-4daf-b575-a858688799eb">
This client retrieval data is normal.

**Comment by Kevin-FF-USA** [comment]
DataCap refreshed: https://filecoinpulse.pages.dev/allocator/f03019858/#pageparamsallocator_id
closting Issue
