### ISSUE TITLE
Community Diligence Review of Opengate Allocator

### ISSUE THREAD

**Issue by OpenGate01** [filecoin-project/Allocator-Governance#128]
Community Diligence Review of Opengate Allocator

Allocator Report: https://compliance.allocator.tech/report/f03019921/1723594234/report.md

Client 1:
https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/6
DC Distributed: 250T - 500T - 250T
 1. There is a verified and publicly disclosed KYC process to authenticate client identities.
 2. The geographical distribution of nodes in the CID report is compliant and aligns with the conditions previously disclosed by the client.
 3. The retrieval rate in the second report has significantly improved compared to the first.
 4. The client does not respond soon, we have closed the ticket until they resubmit their request.
![WechatIMG8385](https://github.com/user-attachments/assets/6591b998-a325-4f53-b081-d189da5b8490)
![MG8386](https://github.com/user-attachments/assets/d6816fa3-31ff-4bbe-9f51-8a2723462806)

Client 2:
https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2

DC Distributed: 500T - 1P - 1P -1P

1. The client's proof is publicly disclosed on github
2. The client discloses the nodes they will cooperate with in advance according to the plan of each round, and the results match
3. The nodes are dispersed enough
![MG8387](https://github.com/user-attachments/assets/a7093182-a53e-4bbf-93c6-0f8b51213098)
![4](https://github.com/user-attachments/assets/4c4b3b05-559a-46cd-ab80-9e18bc730be2)

**Comment by filecoin-watchdog** [comment]
Client 2:
https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2

We have many questions for the allocator and this client about KYB and data storage and retrievals

https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2#issuecomment-2291353488

**Comment by OpenGate01** [comment]
https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2#issuecomment-2294679695

**Comment by Kevin-FF-USA** [comment]
Hello,
Merging this issue with https://github.com/filecoin-project/Allocator-Governance/issues/131 (filed for the same org)

**Comment by Kevin-FF-USA** [comment]
@galen-mcandrew will be responding shortly from Governance review

**Comment by galen-mcandrew** [comment]
Looks like some confusion here. Issue https://github.com/filecoin-project/Allocator-Governance/issues/131 listed OpenGate and this team's compliance report (with address f03019921) in the header of their issue.

**Comment by galen-mcandrew** [comment]
From investigation, this allocator is working with two clients currently.

Their largest client, [ANE](https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2) has 3 allocations to reach 2.8PiB. This does not match the allocator's tranche schedule, with a stated max of 80TiB (question 30 is a [Google spreadsheet](https://github.com/filecoin-project/notary-governance/issues/1020)), screenshot below to capture version. This client also has some flags in the community, regarding their authenticity as the proper data owner. Despite being an Australian education platform with private encrypted data, this client claims they are only working with SPs in China. This is counter to claims we have heard in the past regarding data provenance and geographic restrictions on education datasets within Australia. Additionally, this data has extremely low retrieval rates and some evidence of CID sharing. Additionally, multiple SPs this client is working with have the same owner (such as https://filfox.info/en/address/f02827151 and https://filfox.info/en/address/f02827694).

The other client [Cabin VC](https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/6) was also initially allocated more DataCap than allowed per allocator's application. There is some evidence of KYC diligence here, as well as pausing due to client inactivity.


Overall, there is mixed evidence of diligence and compliance. Specifically:

- inaccurate DataCap tranche distributions
- very low retrieval
- flagged data ownership and authenticity

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

Given this mixed review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 2.5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

@OpenGate01 can you verify that you will enforce program and allocator requirements?  (for example: public diligence, tranche schedules, and public scale retrievability like Spark). **Please reply here with acknowledgement and any additional details for our review.**


![Screenshot 2024-09-04 at 2 52 26 PM](https://github.com/user-attachments/assets/d5d44705-c3e9-4a06-8260-0bb5f17712ab)

**Comment by OpenGate01** [comment]
Hello @galen-mcandrew

1. Regarding the allocation rule mentioned in the screenshot, I would like to clarify that the amount of DataCap granted in each tranche doubles from the previous allocation. The distribution rule is half of the initial weekly request amount, with each subsequent tranche being twice the size of the last, until it reaches 1PiB. This process is ongoing.
2. During my routine checks, I discovered the issue with the cid issue, and the client responded promptly. You can view the details here: https://github.com/OpenGate01/Allocator-Pathway-OpenGate01/issues/2#issuecomment-2296114193. The concerns raised on the other application have been resolved, and there have been no new issues since.
3. As for the client ANE, we have met with them in Australia and are familiar with their data and operations. They have agreed to select their SPs independently, which was a mutually understood arrangement.
4. Regarding retrieval rates, you can track the improvement from earlier reports to the latest report here: https://compliance.allocator.tech/report/f03019921/1726012870/report.md. Initially, many SPs didn’t support Spark (this was a broader issue across the community), but now almost all SPs in use have integrated Spark, and the success rate has steadily improved.
5. In my routine reviews, I regularly follow up with clients. If a client remains inactive and doesn’t respond for an extended period, I will close their application.

Thank you for your understanding. We are actively engaging with many Australian clients, both online and offline, and one of our goals is to help more Australian data clients utilize Filecoin paid deal storage.

**Comment by Kevin-FF-USA** [comment]
DataCap Issued: https://filecoinpulse.pages.dev/allocator/f03019921/#pageparamsallocator_id
closing Issue
