### ISSUE TITLE
Community Review of Venus Fil+ Datacap Allocator (VFDA)

### ISSUE THREAD

**Issue by VenusOfficial** [filecoin-project/Allocator-Governance#149]
Allocator Application https://github.com/filecoin-project/notary-governance/issues/1035

As the owner of the Venus official account, we are dedicated to serving the community through our allocator. However, we must admit that we initially struggled to balance the quantity of clients with the quality of data. Recognizing these challenges, we have reallocated more resources to enhance the DC distribution process. We have implemented stricter KYB and KYC processes for DC applications, addressing data sharing issues among different clients. Regarding data retrievability, we have communicated with the Venus development team to drive the implementation of SPARK support in the Venus Droplet function. We are also in touch with the SPARK team to understand the timeline for the availability of retrievability for DDO, expected in September or October this year.

We acknowledge the difficulty of maintaining both high quality and high quantity simultaneously. After learning from the first round of DC distribution, we are confident in our performance for the next round of DC replenishment. To continue our support and commitment to the community, we sincerely apply for 10 PiB DC in this round.

**Comment by filecoin-watchdog** [comment]
Allocator Compliance Report: https://compliance.allocator.tech/report/f03019831/1726185759/report.md

[Example 1](https://github.com/VenusOfficial/Pathway-VFDA/issues/7)
Allocator claimed the cheating closed client’s application, gov team should follow up.

[Example 2](https://github.com/VenusOfficial/Pathway-VFDA/issues/10)
The allocator closed the application without additional explanation while the client still had DC to spend. They explained themselves after a follow-up question that they had discussed with the client offline. The gov team should follow up. 

[Example 3](https://github.com/VenusOfficial/Pathway-VFDA/issues/15)
The allocator closed the application due to never using the DC. Should DataCap be revoked?

[Example 4](https://github.com/VenusOfficial/Pathway-VFDA/issues/20 )
The allocator granted DC before asking for KYB.   
Gave 200TiBs and then found CID issues. 

SPs provided:
f01114587
f02002888
f02003866
f02003888
f0522948
f0867300
f01228008
f01228000
f02002288
f02104858
F02006999

SPs used for deals:
[f02894286](https://filfox.info/en/address/f02894286)Seoul, Seoul, KR
[f02870401](https://filfox.info/en/address/f02870401)Jakarta, Jakarta, ID
SPs do not match. Retrieval rate below 1%.


[Example 5](https://github.com/VenusOfficial/Pathway-VFDA/issues/22)
Private Commercial/Enterprise
No KYB process is documented.
SPs were being updated several times.

CID report: https://check.allocator.tech/report/VenusOfficial/Pathway-VFDA/issues/22/1722942268616.md

SPs provided:
1，f03136895 Virginia, USA,
2，f03087482 Virginia, USA
3，f03106356 Virginia, USA,
4，f02894286 Seoul, South Korea
5，f01100139 Japan

SPs used for deals:
[f02894286](https://filfox.info/en/address/f02894286)Seoul, Seoul, KR
[f02870401](https://filfox.info/en/address/f02870401)Jakarta, Jakarta, ID

1 of 2 SPs doesn’t match the original list.


[Example 6](https://github.com/VenusOfficial/Pathway-VFDA/issues/26)
The client asked for 2 PiBs, but the allocator agreed to grant only 1 PiB. The application closed after using all DC. 



Across all applications no KYC process is documented (no KYB for private commercial/enterprice in example 5). Allocator says they are doing KYC/KYB through the meetings, Gov team should follow up.
Only 4 out of 9 Allocator’s clients have run the CID checker report. If the allocator doesn’t use these reports, how do they conduct diligence checks?
Only 1 out of 37 SPs has a retrieval rate of over 20%.
The allocator was declared to use only clients and SPs in Asia, while they have clients from America.
Clients #22 and #40 are the same clients - why separate applications? Gov team should follow up.

**Comment by VenusOfficial** [comment]
@filecoin-watchdog First of all, thank you very much for the comments. Here are some explanations.

**Comment by VenusOfficial** [comment]
@Kevin-FF-USA 
I already responded on September 14. Could you please check? Thank you.

**Comment by galen-mcandrew** [comment]
Responding to some of the above comments:

> Example 3: It would be helpful if someone could explain how to revoke unused DataCap. From our understanding, unused DataCap is automatically revoked after 80 days.

DataCap is NOT automatically revoked. The FIDL team has been working to create a front-end tool for removing DataCap from a client. This flow kicks off two bot 'notary' messages on-chain, but still requires the Gov Team and RKH to review and sign-off on the removal. There is also work being done with the new "meta-allocator" structure, where allocators would have more controls over DataCap given to clients; specifically, an ability for the allocator to revoke DataCap they issued to a client WITHOUT involving a second allocator/RKH.

Overall, there is good acknowledgement of the issues, with some clear evidence of allocator interventions for clients that are not following best practices. This type of intervention, with the allocator reviewing and closing out applications, is a good sign. However, we would like to see some additional standardization of the diligence and KYC process. Going forward, we hope to see additional evidence of data distribution and retrieval standards.

Given the diligence evidence and retrieval we are seeing, we are requesting an **additional 5 PiB of DataCap from RKH** to support this allocator increasing their compliance and alignment.

**Comment by VenusOfficial** [comment]
@galen-mcandrew 
Thank you for the instructions on DC revocation and your comments on compliance. We look forward to trying the new "meta-allocator" for all its functions. We will continue to improve our performance in the areas emphasized in your feedback.

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
f2hxivxs3we5afsuyx32lwwn44evopz7yea2fsmhy
