### ISSUE TITLE
2nd Community Diligence Review of Genesis Allocator

### ISSUE THREAD

**Issue by Chuangshi1** [filecoin-project/Allocator-Governance#154]
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1019
First Community Diligence: https://github.com/filecoin-project/Allocator-Governance/issues/64

Allocator Report:  https://compliance.allocator.tech/report/f03019845/1725409611/report.md
Since last community diligence and we got a refresh of 5 PiB Datacap, the following are the updates for the 2nd Community Diligence Review:
 We served 2 clients (one old and one new)with 4PiB in the new process
1.The new client: https://github.com/Chuangshi1/Genesis/issues/38    at present distribute 3.5PiB   
f03166666 Hongkong
f03166668 Hongkong
f02368946 Huhehaote
f02362412 California
f02639492 California
f02822222 Hong Kong
Here are the SPs that they offered and they are same with the CID checker report.
The Spark retrieval rate amost 75%. It will be improve gardually.
https://check.allocator.tech/report/Chuangshi1/Genesis/issues/38/1725420347448.md
![image](https://github.com/user-attachments/assets/b5992616-3594-4916-ac75-1b78b881011a)
2. The old client: https://github.com/Chuangshi1/Genesis/issues/20     at present distribute 0.5PiB
https://check.allocator.tech/report/Chuangshi1/Genesis/issues/20/1725432227836.md
The CID report show that the Spark retrieval rate still low. So according to our distribute roles it was closed. And The Sps that will be marked as Not up to standard.
![image](https://github.com/user-attachments/assets/be352ec4-1474-4fac-b25d-75c0d9841310)

**Comment by Chuangshi1** [comment]
@Kevin-FF-USA

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1019)
[First review](https://github.com/filecoin-project/Allocator-Governance/issues/64)
2nd allocation date: 2024/08/07

[Issue #20](https://github.com/Chuangshi1/Genesis/issues/20)
SPs provided:
f01660008 India
f03126600 CN m
f03010701 CN
f03099903 HK m
f01730296 HK

SPs used for deals:
[f03098989](https://filfox.info/en/address/f03098989) HK
[F03099903](https://filfox.info/en/address/f03099903) HK
[F03139960](https://filfox.info/en/address/f03139960) CN
[F02370792](https://filfox.info/en/address/f02370792) CN
[F03096886](https://filfox.info/en/address/f03096886) CN
[F02086562](https://filfox.info/en/address/f02086562) CN
[F03126600](https://filfox.info/en/address/f03126600) CN
[F03145504](https://filfox.info/en/address/f03145504) HK

Only 2 SPs used for deals match the original list. 


On August 14, the CID checker was triggered, and the report showed that the SP’s distribution was:
⚠️ 57.14% of Storage Providers have a retrieval success rate equal to zero.
⚠️ The average retrieval success rate is 0.02%

Why did the allocator decide to grant the next tranche, knowing the results are below acceptable?

**Comment by Chuangshi1** [comment]
Is any update here? @Kevin-FF-USA @galen-mcandrew

**Comment by galen-mcandrew** [comment]
According to the allocator claims, they have distributed almost 5 PiB to only two clients since the last compliance check. While one [client](https://check.allocator.tech/report/Chuangshi1/Genesis/issues/38/1726070211584.md)  is showing improving retrieval rates, other clients are getting multiple tranches without showing signs of improvement. 

For example, it also seems that the client was given 4 allocations and 1.59PiB of DataCap despite [noncompliant deal-making](https://check.allocator.tech/report/Chuangshi1/Genesis/issues/20/1726765998791.md) (no retrievability, duplicate data, poor distribution, etc). Another [client](https://check.allocator.tech/report/Chuangshi1/Genesis/issues/30/1725431758635.md) has received 3 tranches (most recently on[ 7-9-24](https://filfox.info/en/message/bafy2bzaced44kyvchldlqucenrdt4qmltca6yqmmuaubevlgzeharoxm4fu3q?t=1)), despite similarly noncompliant deal-making.

While we want to see allocator interventions, such as the screenshots above showing the allocator asking questions and closing out client applications, it should not take so many subsequent allocations and so much of your overall DataCap allowance before closing out non-compliant clients.

Given these mixed results, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application, and work to intervene sooner with noncompliant clients. If so, we will request an additional **5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03019845

**Comment by willscott** [comment]
Flagging that this allocator, while acting in LDN last year, was the primary datacap provider [1](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1995) for clients that are now onboarding large amounts of data with that datacap without accountability [2](https://filecoinpulse.pages.dev/client/f02192013/).

More accountability is needed here.

**Comment by Chuangshi1** [comment]
> Flagging that this allocator, while acting in LDN last year, was the primary datacap provider [1](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1995) for clients that are now onboarding large amounts of data with that datacap without accountability [2](https://filecoinpulse.pages.dev/client/f02192013/).
> 
> More accountability is needed here.

I'm so sorry. It is my late to see the message. Actually i don't understand what you mean. I support the hashfrog as V4 notory. It is the truth,but it is just notary work.  Now as a V5 allocator, we are still accountability for our clients and filplus government. If there are some mistakes that we made, I am very happy that you can tell us. Thank you.
