### ISSUE TITLE
Community Review of  IPFS Force Allocator

### ISSUE THREAD

**Issue by ipfsforcezuofu** [filecoin-project/Allocator-Governance#168]
Allocator Application https://github.com/filecoin-project/notary-governance/issues/1034

We sincerely apply for 10P to address the unfulfilled DC demand from the first round of assignment and to meet the upcoming demand from clients. Thank you.

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1034)
[Compliance Report](https://compliance.allocator.tech/report/f03019856/1727136124/report.md)

All of the SPs have a retrieval rate below 75%. 
5 out of 8 SPs have a retrieval rate of 0%. 

Example 1:
The allocator in its applications caused a massive amount of confusion, both with its mistakes and inaccuracy in enforcing client information.
The client requested DC from the allocator at the beginning of August. After a series of incomprehensible agreements regarding the final amount of DC that would be granted to the client, the thread was moved to a separate issue on github ([issue 8](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/8)) due to technical problems.
After creating a new issue, the DC requested was given differently (even assuming that the client deducted the DC already granted, it remains unclear why in [issue 8](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/8) he requested 2 PiB, while in [issue 2](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/2) it was 5 PiB, of which 1 PiB was granted and used). At the same time, in [issue 2](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/2), the client explicitly requested an allocation of another 4 PiB (and not 2).

Expanding on the above:
- The client requested 5 PiB in [issue 2](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/2), of which - according to the allocator's application - 0.3 PiB was calculated as the first tranche,
- The allocator asked for KYC and suddenly decided that since it was a new client, he would grant a maximum of 1 PiB. based on which he calculated a new tranche schedule (60 TiB, according to the allocator's application)
Instead of sticking to the established schedule, he mistakenly granted 1 PiB as the first tranche.
- Having realized his mistake, he decided to do compliance checks according to the originally established schedule. Could the allocator justify what would change this while DC had already been granted? If it was a mistake, the allocator should have contacted the governance team to withdraw the granted DC.

Apart from that, all SPs of this client have a retrieval rate of <5%.


[Example 2](https://github.com/ipfsforcezuofu/ipfsforce-allocator/issues/15)
The allocator did better with the next client, but the client claims to be using 2 SPs, while the allocator application claims to require 5 replicas and SPs each. Has the allocator tried to clarify this with the client? The GitHub issue does not provide an answer to this question.

Side note: Why has the client asked for 3PiB, while they claim one copy will be 250TiB and there will be 4 replicas? It gives 1 PiB; what is the extra 2 PiB needed for?

**Comment by galen-mcandrew** [comment]
Based on the investigation and details provided, we are seeing mixed compliance results. Some areas for this allocator to focus on should include:

- Verifying public client application details in GitHub, and providing diligence evidence for future bookkeeping investigations
- SP lists before and after allocations, with explanations from clients when there are changes made
- Investigating overall dataset size, replicas, and total DataCap requested calculations to avoid unnecessary sector padding
- Encouraging/requiring clients to work with SPs that are showing strong compliance and retrieval rates, rather than waiting for future DDO updates. For example, we are seeing increasing numbers of SPs that are consistently reporting over 75% retrieval rates

Given this review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application, with some extra focus on these areas. If so, we will request an **additional 5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by Kevin-FF-USA** [comment]
DataCap was refilled.
https://datacapstats.io/notaries/f03019856
