### ISSUE TITLE
3rd Community Diligence Review of EF Allocator

### ISSUE THREAD

**Issue by Lind111** [filecoin-project/Allocator-Governance#185]
[Record of last review](https://github.com/filecoin-project/Allocator-Governance/issues/80)

https://compliance.allocator.tech/report/f03014490/1728259518/report.md

This datacap has been assigned to the following two clients

https://github.com/Lind111/EF/issues/27

https://github.com/Lind111/EF/issues/9

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1056)
[Compliance Report](https://compliance.allocator.tech/report/f03014490/1728345918/report.md)
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/12)
[2nd Review](https://github.com/filecoin-project/Allocator-Governance/issues/80)

1st Review score: 2.5PiB granted
2nd Review score: 5PiB granted

2nd allocation on 9/17

DC granted to two clients on this round:
[New client](https://github.com/Lind111/EF/issues/27)
[Ongoing client](https://github.com/Lind111/EF/issues/9)

[Example of ongoing client](https://github.com/Lind111/EF/issues/9)
The Client has stored 13 replicas even though 11 were declared. The Allocator contacted the client for further clarification.
This client works with as many as 17 SPs, 4 of which have a retrieval rate of 0%.

[Example of new client](https://github.com/Lind111/EF/issues/27)
The Client said the proposed dataset wasn’t stored on Filecoin before, but that’s inaccurate. The previously sent dataset might be irretrievable, but the Client and the Allocator should have checked that and explained accordingly.  

Since June 2024, the client has cooperated with several different allocators on other datasets. All those issues are still open, and DC was granted in each case. The gov team should follow up. 

The retrieval rate oscillates between 49-70%

According to the compliance report there are 3 allocations, but the github repo only confirms 2. How did the 3rd allocation get transferred?

The Allocator does KYC processes through e-mail. The Gov team should follow up.

**Comment by Lind111** [comment]
>The Client has stored 13 replicas even though 11 were declared. The Allocator contacted the client for further clarification.

The customer has provided an explanation and I will consider closing the issue and letting the customer reapply
![image](https://github.com/user-attachments/assets/4ed2ae22-28bb-4de2-a2cd-455421b2ad93)

>According to the compliance report there are 3 allocations, but the github repo only confirms 2. How did the 3rd allocation get transferred?

Triggered a bug when signing
https://github.com/fidlabs/allocator-tooling/issues/77

**Comment by Lind111** [comment]
If there are any other questions, please point them out specifically, thanks!

**Comment by Lind111** [comment]
@filecoin-watchdog @Kevin-FF-USA @galen-mcandrew Hi
 It's been three weeks, any updates here please?

**Comment by galen-mcandrew** [comment]
Overall good diligence and compliant behavior. It would be good to see how this allocator is investigating clients that are working with multiple allocator pathways. It is reasonable for a client or data preparer to be working with multiple teams, but there should be investigation, diligence, transparency, and justification for that behavior.

Perhaps your team is able to help work on this, and make some additional developments, suggestions, or tools for the community.

At this time we are requesting **10 PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by Lind111** [comment]
Thanks @galen-mcandrew
