### ISSUE TITLE
Community Review of QC Data Center Allocator

### ISSUE THREAD

**Issue by luhong123** [filecoin-project/Allocator-Governance#186]
Latest Compliance Report: https://compliance.allocator.tech/report/f03014608/1728349006/report.md

https://github.com/luhong123/QC-Data-center/issues/3

https://github.com/luhong123/QC-Data-center/issues/11

KYC exists

Retrievals look good for SP and distribution looks good

**Comment by filecoin-watchdog** [comment]
[First Review](https://github.com/filecoin-project/Allocator-Governance/issues/140)
[Compliance Report](https://compliance.allocator.tech/report/f03014608/1728349006/report.md)
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1071)

DC granted to two clients on this round:
[New client](https://github.com/luhong123/QC-Data-center/issues/11)
[Ongoing client](https://github.com/luhong123/QC-Data-center/issues/3) 

The ongoing client was covered in the previous report. Nothing has worsened since then. 

---
The first thing that catches the eye of the new client is that one dataset was declared at 1.32 PiB. 8 replicas give about 10PiB, while the client asked for 5PiB.

This dataset was stored several times before on the Filecoin network. Why was another copy needed?

The allocator asked additional questions and asked for geographic information of one of the SPs. 

SPs list provided:
f03100009 Hong Kong
f01084941 Hong Kong
f03100002 Shenzhen
f03100000 Shenzhen
f01975299 Shenzhen
f01084413 Changsha
f03161261 New York
f03192503 Hong Kong
f03189917 Dulles

SPs used for deals:
 f03100009
 f03216485
 f01084941
 f03100002
 f01975299
 f03100000
 f01084413
 f03161261
 f03189917
 f03214920
 f03192503

The provided list of SPs includes 9 IDs, while the list of SPs used for deals includes 11 (the last two on the latter list weren’t listed originally). 

---
In general, the Allocator keeps asking questions when something seems off and runs CID Reports often.

**Comment by luhong123** [comment]
>This dataset was stored several times before on the Filecoin network. Why was another copy needed?

I'd like to know how I'm supposed to check the records for this.

>The provided list of SPs includes 9 IDs, while the list of SPs used for deals includes 11 (the last two on the latter list weren’t listed originally).

I asked the client yesterday and he has explained accordingly
![image](https://github.com/user-attachments/assets/3883da1b-ba22-4068-981e-24bff235f9cd)

But considering all the reasons for this new client, I will [close this DataCap Application](https://github.com/luhong123/QC-Data-center/issues/11) and stop distributing the remaining DCs
![image](https://github.com/user-attachments/assets/0e5c4192-ac33-4b97-bda4-ed5040e9ca59)


>In general, the Allocator keeps asking questions when something seems off and runs CID Reports often.

Since the previous week was China's National Day, I was away from work for about 10 days, so I'll pay attention to that later on

**Comment by luhong123** [comment]
@filecoin-watchdog Thank you for your review

**Comment by filecoin-watchdog** [comment]
@luhong123 

> I'd like to know how I'm supposed to check the records for this.

It might be done in several ways:
1. Through [allocator.tech](https://allocator.tech/), by searching for dataset owner:
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/c938fafe-709e-497f-ac6a-549e00b381ba">

2. By searching in this archive repo: [filecoin-plus-large-datasets](https://github.com/filecoin-project/filecoin-plus-large-datasets) for dataset owner, storage link, dataset website etc. It requires careful analysis but gives a room to ask additional questions to clients. 
<img width="1717" alt="Screenshot 2024-10-09 at 11 37 08" src="https://github.com/user-attachments/assets/851317c1-da1f-4256-96fc-207b1d0cb101">

**Comment by luhong123** [comment]
@filecoin-watchdog Got it,thanks

**Comment by galen-mcandrew** [comment]
In addition to the above tools, we also see allocators using [this client database](https://filecoinpulse.pages.dev/clients/) and searching for the client name. We understand this process is not ideal, and we would love to see some additional tools or proposals from the community for improvements.

Additionally, checking this [larger client](https://check.allocator.tech/report/luhong123/QC-Data-center/issues/3/1728283217627.md) as well as the other [smaller client](https://check.allocator.tech/report/luhong123/QC-Data-center/issues/11/1728237422924.md), and seeing some duplicate data issues with SPs. 

Despite these issues, we are generally seeing good compliance and diligence on this pathway. We are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application, with some extra focus on these areas: 

- continuing to improve retrieval rates
- investigating overall dataset size, replicas, and total DataCap requested calculations to avoid unnecessary sector padding
- investigating data prep details from clients

If so, we will request an **additional 10PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

**Comment by luhong123** [comment]
Will follow up on these issues, thanks!

**Comment by Kevin-FF-USA** [comment]
DataCap has been refilled.
https://datacapstats.io/notaries/f03014608
