### ISSUE TITLE
Community Review of RFfil

### ISSUE THREAD

**Issue by MikeH1999** [filecoin-project/Allocator-Governance#188]
Latest Compliance Report:https://compliance.allocator.tech/report/f03014594/1728521303/report.md

Record of previous review:https://github.com/filecoin-project/Allocator-Governance/issues/117

DC for this round have been issued to
https://github.com/MikeH1999/RFfil/issues/43

https://github.com/MikeH1999/RFfil/issues/41
This client was closed due to non-compliance with some of the rules Issues

**Comment by filecoin-watchdog** [comment]
@MikeH1999 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1054) 
[Compliance report](https://compliance.allocator.tech/report/f03014594/1728521303/report.md) 
[First Review](https://github.com/filecoin-project/Allocator-Governance/issues/11) 
[Second Review](https://github.com/filecoin-project/Allocator-Governance/issues/117) 

1st Review score: 2.5PiB granted
2nd Review score: 5PiB granted (9/17)

[Example 1](https://github.com/MikeH1999/RFfil/issues/43)
What is the strategy with this client? Initially, he asked for 5 PiB in another app and due to the STFIL incident, a new app was created, but this time asking for 10 PiB. Why? Was this justified in any way?

All SPs on the list match the provided list of 11 SPs (6 SPs have been used for the deals so far).
The retrieval rate oscillates between 51-63%. It could be better, as the recommended retrieval rate is 75%. 

Minor data duplications(<1%) are observed across all SPs. The Allocator should pay attention to this.


[Example 2](https://github.com/MikeH1999/RFfil/issues/41)
In this case, DC wasn’t granted, but the Allocator made a good effort to get additional info from the client and ended up realising it was a non-compliant client. This is a good investigation example.

**Comment by MikeH1999** [comment]
>What is the strategy with this client? Initially, he asked for 5 PiB in another app and due to the STFIL incident, a new app was created, but this time asking for 10 PiB. Why? Was this justified in any way?

At first I had the same concern, so I made comparisons as well as asked questions

![image](https://github.com/user-attachments/assets/273489a5-ce33-4aa7-9bc8-f5b0d0287a86)
![image](https://github.com/user-attachments/assets/2174ab48-c76e-47b0-9d96-d18e999a5a4e)
My understanding is that this may be the second set of data

So I asked him to provide the data to prove
https://github.com/MikeH1999/RFfil/issues/43#issuecomment-2375625847
![image](https://github.com/user-attachments/assets/e6e39e6a-c774-4dfe-a48e-2f712c9780e3)

In conjunction with the first application, I video verified with him and checked the size of his server and I don't think it's a problem
https://github.com/MikeH1999/RFfil/issues/6#issuecomment-2019338602
![image](https://github.com/user-attachments/assets/11fecfe6-948e-4517-806f-5c69aae80b10)

Including recently I see that he has applied to join the allocator ranks, so I'm sure there is more quality data to bring into filecoin as well
Here's a link to his application:https://github.com/filecoin-project/Allocator-Governance/issues/76

**Comment by MikeH1999** [comment]
>All SPs on the list match the provided list of 11 SPs (6 SPs have been used for the deals so far).

I've been following up on this issue.
![image](https://github.com/user-attachments/assets/1d30e09c-cfca-4804-9815-0f0c58d38f3b)
![image](https://github.com/user-attachments/assets/8d136ebc-bede-48b0-a0d3-997edb4d515a)

**Comment by MikeH1999** [comment]
>The retrieval rate oscillates between 51-63%. It could be better, as the recommended retrieval rate is 75%.

This is a question I also asked my client, as shown here
![image](https://github.com/user-attachments/assets/0443fc2d-0e69-4c93-a653-c53b5501c9c7)

**Comment by MikeH1999** [comment]
>Minor data duplications(<1%) are observed across all SPs. The Allocator should pay attention to this.

On that note, I see in the bot report that less than 20% duplication is allowed
>Storage provider should not be storing duplicate data for more than 20%.

Plus my point,I think the customer stored data has been sent to the SPs, but the SPs may have had sealing failures, so there may be some duplicates that go to make sure that most of the data was sealed successfully and stored successfully

@filecoin-watchdog I'd like to know your thoughts on this issue and have ensured that I follow up with a review request, thanks!

**Comment by MikeH1999** [comment]
@filecoin-watchdog Lastly, thank you for your review.

**Comment by Kevin-FF-USA** [comment]
Hi @MikeH1999,
The diligence has been under review and should be completed with a comment from Galen shortly.

**Comment by galen-mcandrew** [comment]
Given the evidence presented and good diligence, we would like to request an **additional 10PiB of DataCap.** 

As noted, the allocator should continue monitoring the clients and SPs that they are approving, to watch for duplicates, sealing failures, and other issues that may arise. Some duplication is reasonable and expected, to help make sure dataset integrity is maintained.

**Comment by MikeH1999** [comment]
@galen-mcandrew @Kevin-FF-USA Thanks
