### ISSUE TITLE
Community Review of FILWALLET

### ISSUE THREAD

**Issue by a1991car** [filecoin-project/Allocator-Governance#189]
Notary Public Application Form: https://github.com/filecoin-project/notary-governance/issues/1044
Compliance report: https://compliance.allocator.tech/report/f03013312/1728609650/report.md

Customer 1: https://github.com/a1991car/Allocator-Public-Data/issues/3
Customer 2: https://github.com/a1991car/Allocator-Public-Data/issues/14
Customer 3: https://github.com/a1991car/Allocator-Public-Data/issues/16

Our 5PiB has been used up and we hope to be able to recharge in the next round.

**Comment by filecoin-watchdog** [comment]
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1044)
[Compliance Report](https://compliance.allocator.tech/report/f03013312/1728955506/report.md)

[1. Digital Earth Africa #3](https://github.com/a1991car/Allocator-Public-Data/issues/3)
DC granted: 3PiB
—
Instead of a data sample, a website was provided, which does not contain any data to download. The allocator did not ask about the method of preparing the data, did not ask any additional questions.

The data proposed by the client was stored on filecoin many times. A few examples:
https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+Digital+Earth+Africa&type=issues
https://github.com/TVLimited/top-value-storage/issues/13
https://github.com/Origin-Storage-IO/future-storage/issues/10
https://github.com/Chuangshi1/Genesis/issues/12
Many more examples are available for comparison. Please refer to the search results for "Digital Earth Africa" ​​using allocator.tech

The above examples contain different datasets for DE Africa, however it is unknown which ones were used by the client in question as the allocator did not ask any additional questions.

SPs provided:
f02951064, ZheJiang-JinHua - 
f02984282, HeNan-ZhengZhou -
f0122215, ShanDong-QingDao - 
f0427989, ShanDong-QingDao - 
f02942808, GuangDong-ShenZhen
f02894875, JiangXi-FuZhou

SPs used for deals: 
f03035656
f02894875
f02200472
f02942808
f03083270
f03081864
f03072985
f03142258
f03086293
f02824216
f03068013
f01025366
f03074163
f02951213

Only 2 SPs match the list provided by the customer. The original list contained 6 SPs, the actual list contains 14.

In allocator's application it was said that Allocator will require 3 different regions from clients. SPs provided by client were in one region and allocator did not respond. Actual SPs provided by client are from different regions but looking at this application it looks like a lucky coincidence. Please correct me if I am wrong.

11 of 13 SPs have a retrieval rate of 0 or unavailable. 
Only one SP has a retrieval rate of over 75%.

Lastly, according to the allocator application, the first tranche should be 5% of the total DC, but in this client's case, it was 10%. Why this inconsistency?

[2. LAMOST DR7 #14](https://github.com/a1991car/Allocator-Public-Data/issues/14)
DC granted: 0.75PiB
—-
The list of SPs provided matches the list of SPs used for deals, but 4 out of 7 allocators have a retrieval rate below 70%. 

This client attempted to get a DC for the same dataset from a [different allocator](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/41). While this is not the subject of this review, this client still requested a DC renewal from a different allocator on October 8 in the comment, while the application in question is from September.

A dataset with this name was stored on filecoin multiple times. Although these may be different datasets, the client should prove their uniqueness, which was not the case. Has the allocator questioned this?
Examples:
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/41
https://github.com/LendMi-Finance/LendMi-Storage/issues/15
https://github.com/amiclan666/WaterdropLab/issues/5
https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+lamost&type=issues

[3. NOAA](https://github.com/a1991car/Allocator-Public-Data/issues/16)
DC granted: 1.24PiB
—
SPs list provided:
f03157883 GuangDong
f02828269 GuangDong
f02825282 HK
f03179570 sg

SPs list used for deals:
f02852273 GB
F02984331 SG 
F02973061 RU
F02883857 SG

No SP matches the provided list. 
2 SP exceeds the allowed 25% of the sealing date.

This dataset was stored many times. NOAA often appears as a dataset in applications, so you need to pay special attention to applications that use these datasets. Below is a link to search just for this dataset. There are 10 search results. https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+noaa-gefs-reforecast&type=issues

With allocator.tech, you can find applications open on 12 other allocators by typing in NOAA's name. Did the allocator ensure that sending more copies of the dataset would be valuable for the network?

**Comment by filecoin-watchdog** [comment]
@a1991car Hi there. I wanted to remind you that the review was done last week.

**Comment by a1991car** [comment]
https://github.com/a1991car/Allocator-Public-Data/issues/3
Thank you for your reminder. This is our first customer, and our team did not pay attention to the issue of SP updates at that time. We mainly focus on retrieval, CID, and data backup, and we always determine the retrieval rate through manual retrieval.
We see that many distributors signed 512TiB in the first round, and as the first customer, we also signed 512T.
![image](https://github.com/user-attachments/assets/2ab0f63f-b5cc-4bce-b4cc-0404de204b94)

However, in the subsequent allocation, we changed 512 to 256
Although we did not intentionally focus on the increase of SP, as SP increases, the number of SP manually retrieved also increases.

![image](https://github.com/user-attachments/assets/458ed241-3a36-4e05-ab1d-f893f3aa455f)

https://github.com/a1991car/Allocator-Public-Data/issues/14
We have noticed that the applicant is seeking DC from multiple distributors, and we believe this is a manifestation of their technical strength and processing experience. https://github.com/Blockchain-World-News/FIL-DC-Allocator/issues
https://github.com/nicelove666/Allocator-Pathway-IPFSTT
https://github.com/filplus-bookkeeping/DAYOU
We noticed that they were seeking help from multiple distributors, which proves that they may be a good customer, so we helped them.
https://github.com/a1991car/Allocator-Public-Data/issues/16
The change in SP for this customer is because the SP they initially filled in does not support retrieval, and they want to delete the CAR file. Therefore, we requested the customer to search for a new SP, but we did not update them in the list.
Thank you for raising the issue of SP disclosure. We will focus on the actual situation of SP.
Thank you for raising the issue of duplicate datasets. Although we have inquired with the client, we may not have been careful enough, and we will focus on strengthening it in the future.
![image](https://github.com/user-attachments/assets/af3d6317-a41c-4ec5-8f10-51dbe802db66)

**Comment by a1991car** [comment]
When a customer applies to us, if it is a new GitHub and has not applied to any allocator, we cannot determine whether the customer has the technical ability, whether they have the ability to find SP, or whether they have abused DC.
If this is an old Github and we see a lot of allocators granting them DCs, then we can confirm that they already have the ability to find SPs, their cooperating SPs are ready to use FIL for staking, and they also have certain technical capabilities.
If customers engage in abusive behavior towards DC, all enthusiastic distributors who have been assigned to them will be punished, not just us. This is an option for distributors to reduce risk sharing.
So, we believe that customers who have received DC on multiple distributors are high-quality customers and old customers on the Filecoin network.

**Comment by galen-mcandrew** [comment]
Given the details shown above and in this [report](https://compliance.allocator.tech/report/f03013312/1730510771/report.md), we are not seeing strong evidence of distinct clients or strong diligence. Specifically:
- existing datasets
- repeat clients
- duplicate data
- low retrieval rates
- low regional distribution
- VPN usage with minimal justification or investigation
- inaccurate SP distribution claims

Given this review, we are requesting that the allocator verify that they will uphold all aspects & requirements of their initial application. If so, we will request an **additional 2.5PiB of DataCap from RKH**, to allow this allocator to show increased diligence and alignment.

@a1991car  can you verify that you will enforce program and allocator requirements?

**Comment by a1991car** [comment]
Of course, we will strengthen the review of clients. Ensure that they comply with regulations.
