### ISSUE TITLE
Community Diligence Review of MetaEra Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#19]
Review of MetaEra Allocations from @cockroachboss
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1029

First example:
DataCap was given to:
https://github.com/CockroachBoss/Allocator-MediaPlatformData/issues/2

Public Open Dataset - key compliance requirement: Retrievability

1st point)
KYC question asked, and client claimed to send via direct message. This is something for gov team to follow up on to confirm.

2nd point)
Allocation schedule per allocator:
The first allocation will be 1/20 of the total application amount, and each allocation will be twice as much as the last time. Until the maximum single amount is 2p. The remaining rounds will continue to be distributed at 2p.
For example:
The client expected 10PiB datacap. 
The first allocation will be 500TiB, the second allocation will be 1000TiB, third allocation: 2000TiB, fourth: 2000TiB, fifth: 2000TiB, six: 2000TiB, seven: 500TiB.

Actual allocation: 1PiB, 1PiB, 1PiB - **this does not follow their guidelines**

3rd point)
SPs provided by client:
f02211572 | Chengdu, Sichuan | MicroAnt
f02814600 | Chengdu, Sichuan| BigMax
f02226869 | Nanchang, Jiangxi | LuckyMine
f02274508 | Hong Kong | H&W
f02329119 | Hangzhou, Zhejiang | Cryptomage
f02837293 | Seoul, Seoul | FiveByte
f01159754 | Singapore, Singapore | VITACapital
f01852363 | Singapore, Singapore | HectorLi
f02321504 | Los Angeles, California | ipollo
f02320312 | Los Angeles, California | R1
f02327534 | Los Angeles, California | ipollo
f02322031 | Los Angeles, California | ipollo
f02320270 | Los Angeles, California | R1
f01853077 | Singapore, Singapore | Alpha100

https://check.allocator.tech/report/CockroachBoss/Allocator-MediaPlatformData/issues/2/1716390793865.md

Actual SPs taking deals
Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f02956383 | Hong Kong, Hong Kong, HKANYUN INTERNET TECHNOLOGY (HK) CO.,LIMITED | 254.00 TiB | 10.67% | 254.00 TiB | 0.00% | -
f02826123 | Shenzhen, Guangdong, CNChina Mobile communications corporation | 131.16 TiB | 5.51% | 131.16 TiB | 0.00% | -
f02948413 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 258.72 TiB | 10.87% | 258.72 TiB | 0.00% | -
f03066382 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 193.25 TiB | 8.12% | 192.25 TiB | 0.52% | -
f03046248 | Hong Kong, Hong Kong, HKChina Unicom Global | 549.56 TiB | 23.09% | 549.56 TiB | 0.00% | -
f03079511 | Hong Kong, Hong Kong, HKChina Unicom Global | 239.09 TiB | 10.05% | 239.09 TiB | 0.00% | -
f02023435 | Hong Kong, Hong Kong, HKHK Broadband Network Ltd. | 35.91 TiB | 1.51% | 35.91 TiB | 0.00% | **78.86%**
f03064819new | Seoul, Seoul, KRKorea Telecom | 539.53 TiB | 22.67% | 539.16 TiB | 0.07% | -
f02826234 | Singapore, Singapore, SGTencent Building, Kejizhongyi Avenue | 178.53 TiB | 7.50% | 140.88 TiB | 21.09% | -

No Sps match
No retrievals enabled, only one SP showing retrievals per Spark reports. Allocator made a comment about this fact, but still gave more DataCap to client.

**Comment by Kevin-FF-USA** [comment]
Hi @CockroachBoss

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/19.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles
![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/76ccf769-7442-48f7-ada1-ad349d1137ad)

**Comment by CockroachBoss** [comment]
Hello
1. kyc's process is in line with my principle and is based on the client's willingness to see whether they are willing to publicly disclose their information. In addition, I did not pay attention to synchronizing these contents with the gov team. If this is required for each application issue of each pathway, please let me know and I will pay attention to it later.
2. This is because it was my first time to use the signature tool and I was not familiar with the tool.  This is not the case in the other application form, I hope you understand.
3. I reviewed the status of allocation based on the checker report. Everything showed normal.

**Comment by galen-mcandrew** [comment]
Based on a further diligence review, this allocator pathway is **partially** in compliance with their [application](https://github.com/filecoin-project/notary-governance/issues/1029).

Specifically: 

- Mixed evidence of diligence with clients (no verification of client claims)
- Allocations did not match tranche schedule (not scaling trust over time)
- Subsequent allocations given despite noncompliant client deal-making, with minimal allocator intervention through comments
- No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

Given this mixed review, we are requesting that the allocator verify that they will uphold **all aspects & requirements of their initial application.** If so, we will request an **additional 2.5PiB of DataCap** from RKH, to allow this allocator to show increased diligence and alignment.

 **@CockroachBoss can you verify that you will enforce program and allocator requirements?** (for example: public diligence, tranche schedules, and public scale retrievability like Spark). Please reply here with acknowledgement and any additional details for our review.

**Comment by CockroachBoss** [comment]
Hello @galen-mcandrew  thank you for your feedback.

First, I want to state that I am willing and will continue to comply with the assigned requirements.

Secondly, for specific issue, I want to say: 

> Mixed evidence of diligence with clients (no verification of client claims)

We conducted due diligence on the clients and had them send us their identification through other channels. (I was not aware of this before and did not require this to be disclosed on GitHub. If this is a necessary condition, I will do so in the future.)

> Allocations did not match tranche schedule (not scaling trust over time)

The allocation amount was because it was my first time using the signature system. The backend automatically displayed the allocation amount as "fixed," which led to giving clients their weekly application amount directly. I have corrected this issue in the second application form.

> Subsequent allocations given despite noncompliant client deal-making, with minimal allocator intervention through comments

My clients are not "trading non-compliant" through my pathway. My pathway does not strictly require the SP encapsulated for the client to exactly match their pre-conceived SP. Because I have dealt with SP, there are not many SPs available to respond to clients' needs in a timely manner, and the daily speed is limited. Therefore, it is entirely reasonable that clients cannot have their anticipated SP encapsulated. I understand them. (But in the future, I will ensure that clients disclose this in the application form in a timely manner.)

> No retrievability for datasets, despite claims of public open data by both allocator and client (not showing distributed network data storage utility)

The data retrieval issue, I believe, is a common problem for everyone now. I have communicated with the clients, and their data is retrievable; it just cannot be displayed on Spark. So, once Spark's technical adjustments are complete, I believe they will have timely results. (and yes, I will ask them to submit proof that their data is retrievable.）


Could you please supplement us according to the normal allocation amount? Thank you for your understanding and support. I will adjust and respond promptly.

**Comment by CockroachBoss** [comment]
Hello @galen-mcandrew @Kevin-FF-USA 
I hope this message finds you well! 
Just wondering what I should do for the next step.  
I am looking forward to your reply, thanks!

**Comment by galen-mcandrew** [comment]
Regarding the client due diligence claims above: if there is nothing public in your bookkeeping repo, then there is nothing for the governance team or others to review and assess diligence. We cannot track down and investigate disparate and scattered databases, spreadsheets, emails, and one-off communications channels to prove compliance. Per your [application](https://github.com/filecoin-project/notary-governance/issues/1029):

> 36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:
GitHub repo, Google spreadsheet

Regarding SP distribution and client-provided SP lists, again please refer to your own allocator application, specifically:

> 25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:
The allocation ratio of the customer's search SP does not need to be evenly distributed, and the maximum allocation of the customer's lead SP is allowed not to exceed 30%. **Customers need to announce the SP of this round in advance before each round of distribution.** Each round of packaging will be compared with the website https://datacapstats.io/ and recorded. If a customer has two consecutive rounds of discrepancies, the allocation will not proceed. Customers need to apply again, and the maximum amount for re-application is 1p. Until the 1p quota package meets the standards, you will not be allowed to apply for more quotas.

We are following through with the 2.5PiB and will reassess for greater compliance. In the meantime, I suggest you review your allocator application, as well as the stated client applications coming to your pathway.
