### ISSUE TITLE
Community Diligence Review of DSPA Allocator

### ISSUE THREAD

**Issue by filecoin-watchdog** [filecoin-project/Allocator-Governance#21]
Review of DSPA Allocations from @pandacrypto
Allocator Application: https://github.com/filecoin-project/notary-governance/issues/1045

First example:
DataCap was given to:
https://github.com/pandacrypto/DSPA-Allocator/issues/6

Public Open Dataset - key compliance requirement: Retrievability

1st point)
KYC questions asked by allocator but gov team follow up needed to confirm.

2nd point)
Allocation schedule per allocator:
First Round: 512 TiB
Second Round: 1 PiB
Third Round: 2 PiB
Fourth Round: 2 PiB
Overall Cap for Each Client: (2 PiB)

Actual allocation:  512TiB, 1PiB - this does follow their guidelines

3rd point)
SPs provided by client:
-f02809368 Tom Liu Japan
f02812314 Jerry USA
f02812307 Alice Xu Singapore
f02814775 Derek Cui Haarlem, North Holland, NL
f02814770 leo Melbourne, Victoria, AU
f02814767 XHS Koren
f02815438 MaiJie India
f02815448 bluesky USA
f02815451 HZZC Canada
f02815456 Xiangyun US
f02953066 bluesky USA
f02956073 Alice Singapore
f02837684 Xunlei HK
f03028412 ZC Guangdong

https://check.allocator.tech/report/pandacrypto/DSPA-Allocator/issues/6/1716396487509.md

Actual SPs taking deals

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals | Mean Spark Retrieval Success Rate 7d
f03028412 | Guangzhou, Guangdong, CNHuawei Cloud Service data center | 99.16 TiB | 8.21% | 99.16 TiB | 0.00% | -
f02953066 | Los Angeles, California, USIPTELECOM ASIA | 148.47 TiB | 12.30% | 148.47 TiB | 0.00% | -
f02227496 | Hong Kong, Hong Kong, HKIPTELECOM ASIA | 101.77 TiB | 8.43% | 101.77 TiB | 0.00% | 0.00%
f02837684 | Hong Kong, Hong Kong, HKIPTELECOM Global | 149.91 TiB | 12.42% | 149.91 TiB | 0.00% | -
f02956073 | Singapore, Singapore, SGIPTELECOM Global | 109.86 TiB | 9.10% | 109.86 TiB | 0.00% | -
f03080854 | Piscataway, New Jersey, USThe Constant Company, LLC | 299.66 TiB | 24.82% | 299.66 TiB | 0.00% | -
f03080852 | Toronto, Ontario, CAThe Constant Company, LLC | 298.55 TiB | 24.73% | 298.55 TiB | 0.00% | -

4 of 7 Sps taking deals match - others unknown and locations need additional review to confirm

No retrievals enabled on any SPs per Spark reports. Allocator gave a 2nd 1PiB allocation with no diligence.

**Comment by Kevin-FF-USA** [comment]
Hi @pandacrypto

On the next Fil+ Allocator meeting we will be going over each refill application. Wanted to ensure you were tracking the review discussion taking place in https://github.com/filecoin-project/Allocator-Governance/issues/21.

If your schedule allows, recommend coming to the May 28th meeting to answer/discuss the issues raised in the recent distributions. This will allow you to faster address - or, the issue in Allocator Governance for ongoing written discussion.

Warmly,
-Kevin
https://calendar.google.com/calendar/embed?src=c_k1gkfoom17g0j8c6bam6uf43j0%40group.calendar.google.com&ctz=America%2FLos_Angeles

![image](https://github.com/filecoin-project/Allocator-Governance/assets/94004586/1703959e-da5d-4468-90b7-af7d33689d7f)

**Comment by galen-mcandrew** [comment]
Based on an additional compliance review, it appears this allocator is attempting to work with public open dataset clients. 

**However, the data associated with this pathway is not currently able to be retrieved at scale, and testing for retrieval is currently noncompliant.**

As a reminder, the allocator team is responsible for verifying, supporting, and intervening with their clients. If a client is NOT providing accurate deal-making info (such as incomplete or inaccurate SP details) or making deals with noncompliant unretrievable SPs, then the allocator needs to intervene and require client updates before more DataCap should be awarded.

Before we will submit a request for more DataCap to this allocator, please verify that you will **instruct, support, and require** your clients to work with retrievable storage providers.

**@pandacrypto can you verify that you will enforce retrievability requirements, such as through Spark?** Please reply here with acknowledgement and any additional details for our review.

**Comment by pandacrypto** [comment]
@galen-mcandrew Yes, as a allocator we will continue to follow Spark retrieval requirements until a better tool comes along. We ask clients to contact SPs to study Spark retrieval principles and adjust the configuration to meet Spark retrieval requirements.
<img width="1013" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/7ae95e3b-a7e5-4f28-a2f2-3ed87c6112bf">


As you can see, the report shows that there is a gradual improvement in the Spark retrieval success rate.

two weeks ago：
<img width="1021" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/0dfa15f5-1798-4e4b-b0ba-f6e0a19250fd">

now：
<img width="985" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/a4f01658-b789-4b35-a883-89ff7347cbff">

**Comment by pandacrypto** [comment]
As the DSPA allocator operator, we appreciate Kevin-FF for assisting us with the preliminary review during the governance meeting. We hope to receive support for 10 PiB DC to facilitate more convenient applications for clients.

The DSPA allocator conducted multiple rounds of KYC in the early stages to ensure data compliance.
<img width="924" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/d712b9fc-7769-4397-aa22-b2510d5c0b69">
<img width="911" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/e8316ff5-2936-4616-b268-a76f93ffcf6d">
<img width="938" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/b60942c5-1b95-4f20-8ca7-791bd7ae5f6c">


Regarding the filecoin-watchdog showing "4 out of 7 SPs reached deals - other transactions unknown," the allocator considers this acceptable because clients can communicate with different SPs before officially distributing data. However, when it comes to actual data storage, factors such as pledge coins, data preparation, network bandwidth, etc., must be considered. We believe that clients are indeed collaborating with the disclosed SPs.

As for Spark retrieval, as mentioned earlier, the success rate of Spark retrieval by SPs has improved, meeting the governance team's requirement of 85%. It is only a matter of time. We have already seen that SPs, clients, and the Spark development team are officially collaborating within the community to improve this.
<img width="1081" alt="image" src="https://github.com/filecoin-project/Allocator-Governance/assets/52273713/40ce04e9-aa21-426a-bea4-4a89a17bcfb0">


Regarding the new 10 PiB DC distribution, we will also encourage more data types to join. If you have any questions, please feel free to contact me.

**Comment by pandacrypto** [comment]
@galen-mcandrew @Kevin-FF-USA 

It's exciting that some of the allocators have already been recharged twice, thanks for letting me know what other information I need to provide to expedite the DC refill!

**Comment by pandacrypto** [comment]
Looking forward to good news!
