### ISSUE TITLE
Second Community Review of Dcent - NC Allocator

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/Allocator-Governance#215]
Latest report: https://compliance.allocator.tech/report/f03018494/1730680343/report.md

Since the allocator has been running, there have been a total of 5 client application requests.

Overall, the SP Spark retrieval success rate has been good. We are in transition period from Lotus-miner to curio and working to improve retrieval further.

Thanks!
```[tasklist]
### Tasks
```

**Comment by filecoin-watchdog** [comment]
@cryptowhizzard 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1058)  
[Compliance Report](https://compliance.allocator.tech/report/f03018494/1731889709/report.md) 
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/18) 
1st Review score: 10PiB granted

9.75 PiB granted to clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| ChildMind Institute | 250TiB | New |
| NOAAWater-Column Sonar Data Archive | 1PiB | Existing |
| HumanPangenome Reference Consortium | 5.5PiB | Existing |
| Hubbletelescope full dataset | 100TiB | New |
| DistributedArchives for Neurophysiology Data Integration (DANDI) | 2.75PiB | New |
| CIDgravity | 250TiB | Existing |

[CIDgravity](https://github.com/cryptowhizzard/Fil-A-2/issues/6)
* The client declared cooperation with 200 SPs (so far, made deals with 20).
* The retrieval shows some SPs with 0% (5 SPs); however, the majority of the SPs have a bearable retrieval level, oscillating between 30-95%.
* The client declared 8 replicas. However, there are already 12. 
* The client explained CID sharing.

[ChildMind Institute](https://github.com/cryptowhizzard/Fil-A-2/issues/13)
* Did the allocator perform the KYC?
* There is no data sample to browse.
* No SP IDs were provided in the form.
* This client used only 60 out of 250TiB and made deals with only 2 SPs, both in the same region. 
* Not enough information on data preparation.

[NOAAWater-Column Sonar Data Archive](https://github.com/cryptowhizzard/Fil-A-2/issues/9)
* Same applicant name as in the previous example of ChildMind Institute.
* There is no data sample to browse.
* No SP IDs were provided in the form.
* Not enough information on data preparation.
* The allocator indicated in the comment that the KYC was also performed for the client and SPs. 
* The client has only 3 SPs, all in the same region. 
* CID sharing occurred.
* 1 SP sealed almost 60% of the data. 

[Hubbletelescope full dataset](https://github.com/cryptowhizzard/Fil-A-2/issues/17) 
* Same applicant name as in previous examples of ChildMind institute and NOAAWater-Column Sonar Data Archive.
* Only half of the DC was used.
* The application was closed due to several issues. 

[HumanPangenome Reference Consortium](https://github.com/cryptowhizzard/Fil-A-2/issues/1) 
* Same applicant name as in previous examples of ChildMind institute, NOAAWater-Column Sonar Data Archive and Hubbletelescope full dataset.
* Similar issues as before: no data sample, lack of information on data preparation.
* Poor retrieval rate.
* Not the best replication. The report says," 68.91% of deals are for data replicated across less than 4 storage providers."
* This dataset was stored before on the filecoin: https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+Human+Pangenome&type=issues
* According to the report (taking into account only the current round), 2 allocations were awarded directly, bypassing allocator.tech. 
* The allocation schedule for this application is unclear to me. I'd love to hear some clarification.

[DistributedArchives for Neurophysiology Data Integration (DANDI)](https://github.com/cryptowhizzard/Fil-A-2/issues/21) 
* Same applicant name as in previous examples of ChildMind institute, NOAAWater-Column Sonar Data Archive, Hubbletelescope full dataset and HumanPangenome Reference Consortium.
* Similar issues as before: no data sample, lack of information on data preparation.
* CID sharing occurred.
* According to the report (considering only the current round), one allocation was awarded directly, bypassing allocator.tech. 
* With only 4 SPs, 2 sealed over 30% of total datacap.
* This dataset was stored before on the filecoin:
https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+DANDI&type=issues

---

Additional questions:
- How is KYC performed?
- Where does the main communication with clients take place?
- What are your guidelines for determining the allocation schedule?

A few notes:
- This allocator leaves little additional information in the applications for future reviews.
- I wonder about this allocator's allocation schedule because it is not entirely consistent with its application. However, considering request sizes, I would like to hear the allocator's opinion on this first.
- The allocator gives much credit to its primary client, based, as I understand it, on the fact that they know each other in person.

**Comment by cryptowhizzard** [comment]
Greetings!

Thanks for the extensive review and we are keen to answer your questions.

---
https://github.com/cryptowhizzard/Fil-A-2/issues/6
The client declared cooperation with 200 SPs (so far, made deals with 20).
The retrieval shows some SPs with 0% (5 SPs); however, the majority of the SPs have a bearable retrieval level, oscillating between 30-95%.
The client declared 8 replicas. However, there are already 12. 
The client explained CID sharing.
---

_Correct.  This dataset is still in progress. We think that sending deals to 20 Sp's is already a performance these days. Julien is working on his own software to distribute deals and is constantly improving to prepare for the future where we are in need to store data from customer in a quick and reliable way. 
For the retrieval rate Boost is a bit shaky. We expect better performance when SP's are migrating to Curio offcourse._


---
https://github.com/cryptowhizzard/Fil-A-2/issues/13
Did the allocator perform the KYC?
There is no data sample to browse.
No SP IDs were provided in the form.
This client used only 60 out of 250TiB and made deals with only 2 SPs, both in the same region. 
Not enough information on data preparation.

---

As the last comment stated -> 
This project is still in early stage. Only Dcent has staged a first bit ( 60 TB ) of the data but we expect other partners to start Q4 2024. 

_We are waiting for the others ( Holon / RMM ) to come online, at that moment we will report them in the issue template. We also intend to move this project to our commercial allocation path as this project will move to the Openpanda assignment. This is the reason no others are reported and we are only at 60 TB. _ 

----- 

https://github.com/cryptowhizzard/Fil-A-2/issues/9
Same applicant name as in the previous example of ChildMind Institute.
There is no data sample to browse.
No SP IDs were provided in the form.
Not enough information on data preparation.
The allocator indicated in the comment that the KYC was also performed for the client and SPs. 
The client has only 3 SPs, all in the same region. 
CID sharing occurred.
1 SP sealed almost 60% of the data. 

-----

Same as Child mind institute. Dcent is the lead SP and is waiting for others to join. For the CID sharing issue we used our remaining datacap that was allocated in other projects in 2023 to do initial testing. We intend to move these set's to the commercial pathway when they continue to participate in the openpanda project.

----
https://github.com/cryptowhizzard/Fil-A-2/issues/17 
Same applicant name as in previous examples of ChildMind institute and NOAAWater-Column Sonar Data Archive.
Only half of the DC was used.
The application was closed due to several issues. 
---

Correct. This project has failed as we had issues with Curio and the migration path. The data is not retrievable the way we want to thus we stopped.

----
https://github.com/cryptowhizzard/Fil-A-2/issues/1 
Same applicant name as in previous examples of ChildMind institute, NOAAWater-Column Sonar Data Archive and Hubbletelescope full dataset.
Similar issues as before: no data sample, lack of information on data preparation.
Poor retrieval rate.
Not the best replication. The report says," 68.91% of deals are for data replicated across less than 4 storage providers."
This dataset was stored before on the filecoin: https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+Human+Pangenome&type=issues
According to the report (taking into account only the current round), 2 allocations were awarded directly, bypassing allocator.tech. 
The allocation schedule for this application is unclear to me. I'd love to hear some clarification.
---

As per may 15th :

Additional comment :

KYC is performed / was already performed.

Bits & Bytes is a split of of Dcent and will focus on future data distribution. They are known irl.
Holon Australia are knowm irl and per contract
DSS Australis are known irl and per contract
RMM Global, China. KYC performed per video and contract.

Until now focus has been on lead SP ( Bits and bytes ) to store the unsealed and sealed copy of first replica and have everything retrievable.
RMM is only storing the sealed replica for security and backup.

Fyi: This dataset's will participate in the OpenPanda project.

and May 28 :

Per request of the governance team :

f02366527, f02982293, f03064136 belong to Dcent.
f03063130 and f03079759 belong to RMM.
f02031042 f03079759 f03063130 belong to RMM

As soon as DSS / Holon start sealing I will update the miner ID's here.

and June 26 :

Client name: New Itime AG Switzerland.
New Itime AG will store 2 replica's of this dataset. 1 replica Sealed + Unsealed and a second replica just sealed.

This client stopped sealing as they lack funds due a hack to their wallet.

-----

https://github.com/cryptowhizzard/Fil-A-2/issues/21 

Same applicant name as in previous examples of ChildMind institute, NOAAWater-Column Sonar Data Archive, Hubbletelescope full dataset and HumanPangenome Reference Consortium.
Similar issues as before: no data sample, lack of information on data preparation.
CID sharing occurred.
According to the report (considering only the current round), one allocation was awarded directly, bypassing allocator.tech. 
With only 4 SPs, 2 sealed over 30% of total datacap.
This dataset was stored before on the filecoin:
https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+DANDI&type=issues
----

_This is the same as my answers above. The CID sharing is logical since we are storing this dataset again as the last time we stored is many deals expired + some SP's left the network._ 


Additional questions:

How is KYC performed?

_Like we said. We know all participants we work with IRL. The only we don't know is RMM. We did KYC per Zoom._

Where does the main communication with clients take place?

_Slack / Telegram_

What are your guidelines for determining the allocation schedule?

_We are trying to be flexible as participants are struggling atm on the Filecoin network. New time had to stop
sealing due to issues , but also many others are struggling to stay alive. The ones who offered cooperation like RMM are served per request by our own deal distribution system. Holon is late in participation but still has intentions to come on board etc. etc. _ 

A few notes:
This allocator leaves little additional information in the applications for future reviews.
I wonder about this allocator's allocation schedule because it is not entirely consistent with its application. However, considering request sizes, I would like to hear the allocator's opinion on this first.

_When we applied as allocator we made a differentiation between a Non commercial pathway ( made for experiments / practice to prepare for the future where we and other participants have to provide commercial services by storing open dataset's from Amazon ) and a Commercial pathway for Solana / Triton for example that serves only payed work / dataset's. We realize that the path of last months was not without hurdles as we had to transition loads of machines from lotus / lotus-miner / boost to Curio with all the challenges that it brought us and still does. However there is light on the end of the tunnel and we are confident that things will improve / already have improved lately.

As for the data sample ... these are all open dataset's available on AWS. It is useless to provide a data sample here but we can always provide those on request _

---
The allocator gives much credit to its primary client, based, as I understand it, on the fact that they know each other in person.
---

_Correct. Given the turbulence in the market's and the products we work with this is the minimum bar height ...  We want to know who we are / were talking to otherwise it does not make sens to provide commercial services in near future  ;-)_

**Comment by Kevin-FF-USA** [comment]
Hi @cryptowhizzard,

Governance team was out for the Thanksgiving holiday last week, but have this with the applications receiving a final audit and verification this week.    Thanks for the detailed reply back to the community and watchdog comments.  

Just wanted to keep you updated, should see the final comment from Galen shortly before this moves to the RKH.  Appreciate your patience and comms, here if you need anything or have questions.

Warmly,
-Kevin

**Comment by galen-mcandrew** [comment]
Appreciate the patience and comms back and forth here. Overall, the role of the allocator is to help verify eligibility for the subsidy (real clients, real data, real distribution) and support client's onboarding data. The goal of the bookkeeping repos is to have an auditable paper trail of this diligence. The allocators can be using these repos to track and log the diligence, without the client necessarily needing to be involved. As always, we want transparency and accountability: if the allocator is submitting comments on behalf of the downstream business clients, that can be fine with sufficient justification. From my understanding, this is the "non-commercial" or open public data pathway, where DCENT is acting as the data preparer, and then distributing those packaged deals to various partner SPs. 

Want to highlight some areas that we would like to see more development going forwards, which may streamline this process overall:

- Clearly enumerated and updated SP id's as well as top-level operators; for example distribution across Holon vs DSS.
- Clear links to data samples. A possible ideal solution would be a dynamic website or dashboard that connected active deals with the datasets.
- Increasing and more consistent retrieval, CID distribution

Overall, this allocator is working to properly package and backup existing public open datasets. We look forward to seeing continued progress and improvements for the entire network. Given this, we are requesting an **additional 20PiB of DataCap** from RKH.
