### ISSUE TITLE
2nd Community Review of CloudX Lab Allocator

### ISSUE THREAD

**Issue by CloudX-Lab** [filecoin-project/Allocator-Governance#218]
Latest Allocator Report: https://compliance.allocator.tech/report/f03019835/1730884084/report.md

2 clients receiving allocations over several rounds.
https://github.com/CloudX-Lab/filecion/issues/17
cid report: https://check.allocator.tech/report/CloudX-Lab/filecion/issues/17/1730369584439.md

https://github.com/CloudX-Lab/filecion/issues/21
cid report: https://check.allocator.tech/report/CloudX-Lab/filecion/issues/21/1730788248830.md

We have requested from client for KYC, latest sp list, and improving success retrieval rate.

[This client](https://github.com/CloudX-Lab/filecion/issues/17) has increasing their retrieval rate. I will update their retrieval rate.

**Comment by filecoin-watchdog** [comment]
@CloudX-Lab 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1001)  
[Compliance Report](https://compliance.allocator.tech/report/f03019835/1732063393/report.md)  
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/152) 
1st Review score: 2.5PiB

Note: The repo configuration for this client seems incorrect, influencing compliance report output (missing issues, incorrect datacap-bot messages). 

2.5 PiB granted to new clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| NOAA | 0.7PiB | Existing |
| POLAR GEOSPATIAL CENTER | 1.7PiB | Existing |

[NOAA](https://github.com/CloudX-Lab/filecion/issues/17)
* The allocator asked additional questions to the form and correctly noted that the data prepared by the client was already stored on the filecoin. However, the client should have specified more precisely what data he plans to store, providing a narrowed scope of data. Especially since, in this case, there is much more data from NOAA, and the topic of storing it in filecoin comes up regularly.
* The allocator pointed out that the SPs list doesn’t match the one provided in the form.
* The newest report shows that 1 out of 6 SPs has a retrieval rate of 0%.
* Was the KYC performed? If so, how was it done?
* According to the allocation schedule described in the allocator application, the first tranche should be 5%, which should be 100TiB for this client, while the first tranche was 256TiB. Why the change?


[POLAR GEOSPATIAL CENTER](https://github.com/CloudX-Lab/filecion/issues/21) 
* this data was stored several times on the filecoin https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+arcticdem&type=issues
* Was the KYC performed? If so, how was it done?
* Some additional questions were asked, yet there is not enough information on data preparation.
* According to the allocation schedule described in the allocator application, the first tranche should be 5%, which should be 100TiB for this client. The first tranche was 516TiB. Also, it was declared that the max allocation per client will be 500TiB, while this client got 767TiB on the third tranche. Why the changes? 
* The latest report shows retrieval at a quite good level, distribution and replicas good.

---

The most important thing in this review, though, is that the allocator has not shown any activity towards becoming an automatic allocator, which is completely inconsistent with the allocator application. This was raised in the last review; unfortunately, nothing has changed.

**Comment by CloudX-Lab** [comment]
Hello @filecoin-watchdog ,

Some time ago, no record showed up on the application after signing. So we asked in slack and submitted this issue. https://github.com/fidlabs/allocator-tooling/issues/90
![image](https://github.com/user-attachments/assets/13c1e615-0b0d-4a46-a26f-b80bbdce0eed)

Yes. We did kyc on our clients every time. We will ask questions about the client's situation in the application, and we will also ask the client to send us an email to confirm their identity. 
https://github.com/CloudX-Lab/filecion/issues/17
![image](https://github.com/user-attachments/assets/8ce61f43-e21f-4953-b421-f7152cd55350)
https://github.com/CloudX-Lab/filecion/issues/21
![image](https://github.com/user-attachments/assets/1c2efa64-d57e-4da7-985d-e6caa44a05e4)

The way we allocate datacap now is in proportion to the actual amount of data and needs of the client. In our allocator work, we've found that our clients have different needs. When we verified the client and believe that the client has the qualification, we currently take to follow the amount of demand in the client's application to make it more convenient for the client for datacap use. This is our test, and we're considering whether the allocation should be performed according to different client types. But we'll discuss the allocation plan next. Thank you for the remind.

We have aimed to create an automated allocator, but in the reality of technical research, we have not yet gotten a good solution. That's why we now prioritize responding to client needs and use manual allocation.

In our allocator work nowadays, we ask our clients to ensure that the retrieval is improved, and this is one of the criteria that we think is very important. We will make further improvements and enhancements to what we have in place, and thank you for your review, which has been very helpful to us.

**Comment by Kevin-FF-USA** [comment]
Hi @CloudX-Lab 

Thanks for providing the additional information.
As more of these refresh requests are processed, greater adherence to the diligence plans in each pathways application will need to be maintained in order to justify receiving additional DC to distribute. Makes it helpful to understand the client distributions and how you are working to support them.

Next step is this application will receive a final review from Galen next week.  
This review will take into account the retrieval rates, Bookkeeping documentation, SPs, As well as past issues that were identified in previous refreshes.  If you have any questions please a comment here in issue, otherwise you will see guidance next week. 

Warmly,
-Kevin

**Comment by galen-mcandrew** [comment]
Based on the investigation, this allocator is attempting to act as a manual pathway and onboarding extraneous copies of already existing datasets, without clear explanations or improvements to those datasets. 

Regardless of the specific issues noted above about the datasets, we agree with the larger compliance issue: there is no longer work or development of an automated pathway. At this time, this allocator is no longer compliant with their original application, for example: 

> 8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?
Please explain the unique aspects of your proposed pathway.
• Intelligent allocation algorithm: Using advanced algorithms to allocate data. Intelligent allocation can be made based on different indicators and conditions, such as priority, applicant domain, etc. Compared to traditional random or manual allocation methods, intelligent allocation algorithms can more effectively match data with applicants, improving the accuracy and efficiency of allocation.
• Data monitoring: The allocator has real-time data monitoring function, which can track and record the data resources used by each applicant. DataCap can keep abreast of the applicant's application progress and make corresponding adjustments and optimizations as needed.
• Feedback mechanism: Through intelligent feedback mechanism, feedback opinions and suggestions from applicants can be collected, and allocation algorithms can be continuously optimized and improved based on these feedback.
• Our allocator provides DataCap with a unique, new, or diverse approach that can distinguish it from other applicants. Can improve the accuracy and efficiency of data allocation, optimize data processing processes.


Given this discrepancy, **we are requesting this pathway is removed.** We invite and encourage the CloudX team to reapply with their new diligence process as a manual allocator.
