### ISSUE TITLE
3nd Community Diligence Review of Enterprise data Allocator

### ISSUE THREAD

**Issue by NDLABS-Leo** [filecoin-project/Allocator-Governance#227]
Community Diligence Review of Enterprise data  Allocator 

Allocator Report: https://compliance.allocator.tech/report/f03012747/1731976608/report.md  

Allocation Record：https://datacapstats.io/notaries/f03012747

This round of review is the second round of 4.5PiBs allocations.

DataCap awarded to:

![image](https://github.com/user-attachments/assets/d1156ee7-f3d7-42d9-b21d-14e4404d138e)

**Comment by filecoin-watchdog** [comment]
@NDLABS-Leo 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1025)  
[Compliance Report](https://compliance.allocator.tech/report/f03012747/1732667814/report.md)  
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/109)  
1st Review score: 5PiB

5 PiB granted to existing clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| TheSecond Life new2 | 2PiB | Existing |
| Mapxus | 400TiB | New |
| eteamxr | 1.27PiB | New |
| ILKLearning | 1.34PiB | New |

[TheSecond Life new2](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/15) 
* The allocator identified a bad report output and requested an explanation from the client.
* The client informed the allocator about new SPs to be used in upcoming rounds before making deals with them. Several additional SPs were used without prior notification (f02826588, f03081958).
* Some duplications occurred (reports are fixed now). 
* mixed retrieval rate
* The allocator and client regularly update the app, report findings and discuss bad report results. a big plus for that.


[Mapxus](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/27) 
* All SPs match the provided list.
* One SP has a retrieval rate that is too low.

[eteamxr](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/21) 
* The allocator reminded the client about the necessity of updating the SPs list (this still needs to be done by the client, as the new report shows additional SPs).
* Two SPs have retrieval rates that are too low.


[ILKLearning](https://github.com/NDLABS-Leo/Allocator-Pathway-Enterprise-data/issues/25) 
* Two new SPs were not updated.
* Two SPs have retrieval rates that are too low.

---

The allocator ensures open discussions with clients, providing valuable insights into the processes. Everything is transparent. The allocator conducts KYB checks and analyzes client forms.

**Comment by filecoin-watchdog** [comment]
Btw, this is the 2nd review, not the 3rd :)

**Comment by NDLABS-Leo** [comment]
> Btw, this is the 2nd review, not the 3rd :)

Sorry for the late reply, and belated Happy Thanksgiving.

Thank you for the reminder.

**Comment by NDLABS-Leo** [comment]
Thank you, @filecoin-watchdog, for your thorough and precise comments.

We acknowledge that there is room for improvement, particularly in two key areas: the retrieval rate of the SPs our clients collaborate with and the timely updates of the SP list. Moving forward, we will focus on enhancing these aspects.

Thank you again for your valuable feedback.

**Comment by galen-mcandrew** [comment]
**Flagging for future audits: this is the second compliance review of the HK CyberPort pathway by ND Labs**

Overall seeing evidence of diligence and compliance. Here are specific areas that need to improve for this next round:

- SP lists need to remain updated and accurate
- Decrease redundant datasets, monitor and intervene when CID sharing occurs
- Increase retrieval 

Additionally, this specific onboarding pathway is (based on my understanding of your [application](https://github.com/filecoin-project/notary-governance/issues/1025#issuecomment-1890592797)) reserved for participants in CyberPort. Given that, it would be good to collect more specific and standard information about your clients. This could be links or some kind of evidence that shows their involvement in that program, and could be collected in the initial client application or in the comments section. This may make future diligence investigation faster and easier, since all of your clients should be able to demonstrate high alignment and existing verification.

Given this review, we are requesting an **additional 10PiB of DataCap** from RKH, to allow this allocator to show increased diligence and alignment.

**Comment by NDLABS-Leo** [comment]
@filecoin-watchdog @galen-mcandrew 
Thank you, we will work hard on these three points.

SP lists need to remain updated and accurate
Decrease redundant datasets, monitor and intervene when CID sharing occurs
Increase retrieval
